#!/bin/bash

. /usr/lib/ayer/functions.sh

source /usr/lib/ayer/functions.sh

target_feature=$(git rev-parse --abbrev-ref HEAD)

cd_to_hoy_top

if [ -n "$1" ]; then
    base_treeish=$1
else
    [ -n "$BRANCH" ] || die "BRANCH must be set in .ayer"
    base_treeish=remotes/origin/$BRANCH
fi

{ echo .; git submodule -q foreach 'echo $name'; } | while read repo_path; do
    cd $hoy_top/$repo_path
    local_commit=$(git rev-parse HEAD)
    remote_commit=$(git rev-parse $base_treeish) || continue
    if [ "$local_commit" == "$remote_commit" ]; then
        continue
    fi
    version=
    for i in *.spec; do
        if [ -f $i ]; then
            version="-$(rpm_get_tag $i version)"
            break
        fi
    done
    echo "$(basename $PWD)$version:"
    git --no-pager log --format='    - %s' $remote_commit..HEAD || true
done
