#!/bin/bash

source /usr/lib/ayer/functions.sh

load_config

version_name="${1%_trunk}"
[ -n "$version_name" ] || die "usage: $(basename $0) version_name"
trunk_name="${version_name}_trunk"

build_commit="origin/$trunk_name"
target_path="dev/$trunk_name"
previous_ref=""
build_release="$trunk_name"

ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_release"

replace_repos "$YUM_REPO_DIR/$target_path"
