#!/bin/bash -e

source /usr/lib/ayer/functions.sh

ayer_init

# Usage: "$0" <project> <refspec> [<target>]

project=${1:?Project undefined.}
refspec=${2:?Refspec undefined.}
target=${3:-test}
repo_ssh=$(gerrit_repo_ssh "$project")


# Basic sanity checks
echo "$project" | fgrep -q '/' && die "Invalid project name"

# XXX: should create temporary path out there? for jenkins we don't need it
git_fetch_refspec "$project" "$repo_ssh" "$refspec"
cd "./$project"
git checkout FETCH_HEAD

script="./.build"
if [ '!' -f "$script" ] ; then
    echo "WARNING: No tests run" >&2
    exit 0
fi

"$script" "$target" || die "Tests failed"

