#!/bin/bash

source /usr/lib/ayer/functions.sh

ayer_init

build_commit=$1
build_user=$2
[ -n "$build_commit" -a  -n "$build_user" ] || die "usage: $(basename $0) build_commit user"

build_user="${build_user%%[!a-zA-Z._-]*}"
[ -n "$build_user" ] || die "bad user name, should begin with [a-zA-Z._-]"

gerrit_query_change "$build_commit"
build_branch=$CHANGE_BRANCH
build_topic=$CHANGE_TOPIC

echo "branch: $build_branch"
echo "topic: $build_topic"

target_path="dev/$build_user/$build_branch/$build_topic"
previous_ref="$build_branch"

ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_branch"

replace_repos "$YUM_REPO_DIR/$target_path"


echo "checking whether build commit can be accepted to trunk"
if ayer-is-acceptable "$build_commit" "$build_branch" >/dev/null; then
    echo "build commit is acceptable"
else
    echo "WARNING: build commit cannot be accepted to trunk"
fi
