#!/bin/bash

source /usr/lib/ayer/functions.sh

load_config

PROG=$(basename "$0")

TEMP=`getopt -n $PROG  -o c:,u: -l commit:,user: -- "$@"` || exit 1
eval set -- "$TEMP"

while [ "$#" -gt 0 ]; do
    case "$1" in
        -c|--commit)
            build_commit=$2
            shift
            ;;
        -u|--user)
            build_user=$2
            shift
            ;;
    esac
    shift
done
[ -n "$build_commit" ] || die "build commit is unknown"
[ -n "$build_user" ] || die "build user is unknown"


commit_info_file=$(mktemp /tmp/ayer.build.XXXXXX)
gerrit_command query "project:$BASE_PROJECT commit:$build_commit" --current-patch-set > $commit_info_file
while read key value; do
    case "$key" in
        branch:)
            build_branch=$value
            ;;
        topic:)
            build_topic=$value
            ;;
        ref:)
            release_refspec=$value
    esac
done < "$commit_info_file"
rm "$commit_info_file"
[ -n "$build_branch" ] || die "build branch is unknown"
[ -n "$build_topic" ] || die "build topic is unknown"

target_path="dev/$build_user/$build_branch/$build_topic"
previous_ref="$build_branch"

ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_branch"
