#!/bin/bash

source /usr/lib/ayer/functions.sh

load_config

PROG=$(basename "$0")

TEMP=`getopt -n $PROG  -o c:,u:,t:,b: -l commit:,user:,branch:,topic: -- "$@"` || exit 1
eval set -- "$TEMP"

while [ "$#" -gt 0 ]; do
    case "$1" in
        -c|--commit)
            build_commit=$2
            shift
            ;;
        -u|--user)
            build_user=$2
            shift
            ;;
        -b|--branch)
            build_branch=$2
            shift
            ;;
        -t|--topic)
            build_topic=$2
            shift
            ;;
    esac
    shift
done
[ -n "$build_commit" ] || die "build commit is unknown"
[ -n "$build_user" ] || die "build user is unknown"
[ -n "$build_branch" ] || die "build branch is unknown"
[ -n "$build_topic" ] || die "build topic is unknown"

target_path="dev/$build_user/$build_branch/$build_topic"
previous_ref="$build_branch"

ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_branch"

replace_repos "$YUM_REPO_DIR/$target_path"


echo "checking whether build commit can be accepted to trunk"
if ayer-is-acceptable "$build_commit" "$build_branch" >/dev/null; then
    echo "build commit is acceptable"
else
    echo "WARNING: build commit cannot be accepted to trunk"
fi
