#!/bin/bash

source /usr/lib/ayer/functions.sh

load_config

trunk_name="${1%_trunk}_trunk"

[ -n "$trunk_name" ] || die "usage: $(basename $0) trunk_name"

build_commit="origin/$trunk_name"
target_path="dev/$trunk_name"
previous_ref=""
build_release="$trunk_name"

ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_release"

replace_repos "$YUM_REPO_DIR/$target_path"
