#!/bin/bash

source /usr/lib/ayer/functions.sh

load_config

version_name="${1%_trunk}"
[ -n "$version_name" ] || die "usage: $(basename $0) trunk_name"
trunk_name="${version_name}_trunk"

git_fetch_repos origin/$trunk_name

cd "${git_dir}/${BASE_PROJECT}.git"
git ls-tree -r origin/$trunk_name | while read mode type hash path; do
    if [ "$mode" == 160000 ]; then
        git_project_dir="$(basename "$path").git"
        cd "$git_dir/${git_project_dir}"
        git push origin :refs/heads/$trunk_name :refs/tags/$version_name
    fi
done

cd "${git_dir}/${BASE_PROJECT}.git"
git push origin :refs/heads/$trunk_name :refs/tags/$version_name

target_path="dev/$trunk_name"
rm -rf "$YUM_REPO_DIR/$target_path"
