#!/usr/bin/python2

import sys
import xml.dom.minidom


def die(msg):
    print >> sys.stderr, msg
    sys.exit(1)

    
def main():
    if len(sys.argv) < 2:
        die("please provide manifest filename")
    dom = xml.dom.minidom.parse(sys.argv[1])
    for elem in dom.getElementsByTagName("project"):
        try:
            print elem.getAttribute("name")
        except:
            pass


if __name__ == "__main__":
    main()
