#!/bin/bash

source /usr/lib/ayer/functions.sh

load_config

base_version="${1%_trunk}"
trunk_name="${2%_trunk}_trunk"

[ -n "$base_version" -a -n "$trunk_name" ] || die "usage: $(basename $0) base_version trunk_name"

# TODO: check for validity base_version, trunk_name

git_repos_dir="${BASE_WORKDIR}/git"

mkdir -p "$git_repos_dir"

cd "$git_repos_dir"
git_fetch_refspec "release.git" "$(gerrit_repo_ssh release)" "refs/tags/$base_version:$trunk_name"
cd ./release.git
git push origin +$trunk_name:refs/heads/$trunk_name
build_commit=$(git rev-parse $trunk_name)

git ls-tree -r $base_version | while read mode type hash path; do
    if [ "$mode" == 160000 ]; then
        cd "$git_repos_dir"
        git_project_dir="$(basename "$path").git"
        origin_path="$(gerrit_repo_ssh "$git_project_dir")"
        git_fetch_refspec "${git_project_dir}" "$(gerrit_repo_ssh "$git_project_dir")" "refs/tags/$base_version:$trunk_name"
        cd "${git_project_dir}"
        git push origin +$trunk_name:refs/heads/$trunk_name
    fi
done

ayer-build-trunk "$trunk_name"
