#!/bin/bash

# arguments: version_name

source /usr/lib/ayer/functions.sh

load_config

function create_and_publish_tag() {
    local git_project_dir="$1"
    git_fetch_refspec "${git_project_dir}" "$(gerrit_repo_ssh "$git_project_dir")" "$trunk_name:refs/heads/$trunk_name"
    cd "${git_project_dir}"
    git tag --force "$version_name" "$trunk_name"
    git push --tags origin
}

version_name="${1%_trunk}"
trunk_name="${version_name}_trunk"

# TODO: check trunk_name for validity
# TODO: manipulate version tree data

build_commit="origin/$trunk_name"
target_path="$version_name"
previous_ref=""
build_release="$trunk_name"

[ ! -d "$YUM_REPO_DIR/$target_path" ] || die "error: release directory \`$YUM_REPO_DIR/$target_path' already exists"

ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_release"

git_repos_dir="${BASE_WORKDIR}/git"
mkdir -p "$git_repos_dir"
cd "$git_repos_dir"
create_and_publish_tag ${BASE_PROJECT}.git

cd "$git_repos_dir/${BASE_PROJECT}.git"
git ls-tree -r "$trunk_name" | while read mode type hash path; do
    if [ "$mode" == 160000 ]; then
        cd "$git_repos_dir"
        create_and_publish_tag "$(basename "$path").git"
    fi
done

replace_repos "$YUM_REPO_DIR/$target_path"
