#!/usr/bin/expect --
#
# Automatically sign rpm packages

for {set i 0} {$i<$argc} {incr i} {
    spawn rpm --addsign [lindex $argv $i]
    expect -exact "Enter pass phrase: "
    send -- "Secret passphrase\r"
    expect eof
}
