#!/bin/bash

. /etc/ayer/functions.sh

previous_branch="${build_version}-trunk"
repo_template=/etc/repo.template

function createrepo_release() {
    cd "$git_repos_dir"
    mkdir -p "$yum_final_repo_dir"
    changelog_file="$yum_final_repo_dir/../Changelog.$feature_branch"
    echo "* $(date '+%a %b %d %Y')" > "$changelog_file"
    while read repo_path; do
        repo_name="$(cut_repo_name "$repo_path")"
        log "generating changelog for $repo_name"     
        cd "$repo_name"
        echo "- $repo_name" >> "$changelog_file"
        git log --format='    - %s' master-git/$previous_branch..origin/$feature_branch >> "$changelog_file"
        cd ..
    done < "$git_repos_list"
}


build_changelog

