#!/bin/bash

source /usr/lib/ayer/functions.sh

target_feature=$(git rev-parse --abbrev-ref HEAD)

cd_to_hoy_top

[ -n "$branch" ] || die "\`branch' must be set in .ayer"

upload_type=drafts

{ git submodule -q foreach 'echo $name'; echo .; } | while read repo_path; do
    cd $hoy_top/$repo_path
    local_commit=$(git rev-parse HEAD)
    remote_commit=$(git rev-parse remotes/origin/$branch || true)
    if [ "$local_commit" == "$remote_commit" ]; then
        continue
    fi
    published_ref=refs/published/$target_feature
    if git rev-parse $published_ref &>/dev/null; then
        difference=$(git rev-list $published_ref..HEAD)
        if [ -z "$difference" ]; then
            continue
        fi
    fi
    git push origin HEAD:refs/$upload_type/$branch/$target_feature
    git update-ref $published_ref HEAD
done
