#!/bin/bash

source /usr/lib/ayer/functions.sh

hoy_init

target_feature=$(git rev-parse --abbrev-ref HEAD)

force=$1

target_branch=$(get_trunk "$target_feature")
username=$(get_username)

upload_type=for

{ git submodule -q foreach 'echo $name'; echo .; } | while read repo_path; do
    cd $hoy_top/$repo_path
    local_commit=$(git rev-parse HEAD)
    remote_commit=$(git rev-parse remotes/origin/$target_branch || true)
    if [ "$local_commit" == "$remote_commit" ]; then
        continue
    fi
    published_ref=refs/published/$target_feature
    if git rev-parse $published_ref &>/dev/null; then
        difference=$(git rev-list $published_ref..HEAD)
        if [ -z "$difference" ]; then
            continue
        fi
    fi
    git push origin HEAD:refs/$upload_type/$target_branch/$target_feature || [ "$force" == -f ]
    git update-ref $published_ref HEAD
done

curl "${JENKINS_BASEURL%/}/job/ayer-build-topic/buildWithParameters" -d "USER=${username}&COMMIT=$(git rev-parse HEAD)"
echo "results: ${YUM_REPO_BASEURL_DEV%/}/dev/$username/$target_branch/$target_feature"
