#!/bin/bash

. /usr/lib/ayer/functions.sh

source /usr/lib/ayer/functions.sh

hoy_init

target_feature=$(git rev-parse --abbrev-ref HEAD)

if [ -n "$1" ]; then
    base_treeish=$1
else
    base_treeish=remotes/origin/$(get_trunk "$target_feature")
fi

{ echo .; git submodule -q foreach 'echo $name'; } | while read repo_path; do
    cd $hoy_top/$repo_path
    local_commit=$(git rev-parse HEAD)
    remote_commit=$(git rev-parse $base_treeish) || continue
    if [ "$local_commit" == "$remote_commit" ]; then
        continue
    fi
    version=
    if which rpm &>/dev/null; then
        for i in *.spec; do
            if [ -f $i ]; then
                version="-$(rpm_get_tag $i version)"
                break
           fi
       done
    fi
    echo "$(basename $PWD)$version:"
    git --no-pager log --format='    - %s' $remote_commit..HEAD || true
done
