#!/bin/bash

source /usr/lib/ayer/functions.sh

hoy_init

git submodule init
git fetch -p origin --recurse-submodules

if [ ! -f .git/hooks/commit-msg ]; then
    # sed produces something like "-P 29418 aababilov@osc-build:hooks/commit-msg"
    scp -p $(git remote show -n origin |grep Fetch | sed -r 's#^.+: +(ssh://)?([^:]+):([0-9]+)/.*$#-P \3 \2:hooks/commit-msg#') .git/hooks
fi
commit_hook=$(readlink -f .git/hooks/commit-msg)
find .git/modules -name hooks -type d | while read hooks_dir; do
    ln -sf "$commit_hook" "$hooks_dir"
done
