#!/bin/bash

source /usr/lib/ayer/functions.sh

target_branch=${1%_trunk}_trunk
target_feature=$2

[ -n "$target_feature" -a -n "$target_branch" ] || die "usage: hoy-feature branch feature"

cd_to_hoy_top

git fetch origin --recurse-submodules
git checkout -t -B "$target_feature" "origin/$target_branch"
git submodule update
git submodule foreach git checkout -t -B "$target_feature" "origin/$target_branch"

if [ -f .ayer ]; then
    sed -i '/^branch=/d' .ayer
fi

echo "branch=$target_branch" >> .ayer
if [ ! -f .git/hooks/commit-msg ]; then
    # sed produces something like "-P 29418 aababilov@osc-build:hooks/commit-msg"
    scp -p $(git remote show -n origin |grep Fetch | sed -r 's#^.+: +(ssh://)?([^:]+):([0-9]+)/.*$#-P \3 \2:hooks/commit-msg#') .git/hooks
fi
commit_hook=$(readlink -f .git/hooks/commit-msg)
find .git/modules -name hooks -type d | while read hooks_dir; do
    ln -sf "$commit_hook" "$hooks_dir"
done
