#!/bin/sh



function get_tag() {
    rpm -q --specfile "$1" --qf "%{$2}\n"| head -1 | sed 's,/,,g'
}
function die() {
    echo "$@" >&2
    exit 3
}


gear_treeish="${gear_treeish:-HEAD}"

RPM_BUILD_DIR=~/rpmbuild/
RPM_SPECS_DIR=${RPM_BUILD_DIR}/SPECS

mkdir -p "${RPM_SPECS_DIR}"

if [ -z "$1" ]; then
    BASE_PATH="$PWD"
    spec_file="$(ls *.spec|head -1)"
elif [ -d "$1" ]; then
    BASE_PATH="$1"
    cd "$BASE_PATH"
    spec_file="$(ls *.spec|head -1)"
else
    BASE_PATH=$(dirname "$1")
    cd "$BASE_PATH"
    spec_file=$(basename "$1")
fi


[ -r "$spec_file" ] || die "cannot find $spec_file!"

cp "${spec_file}" "${RPM_SPECS_DIR}/${spec_file}"
spec_file="${RPM_SPECS_DIR}/${spec_file}"

#sed -i 's/Release: .*/Release:        '$(date +'0.%Y%m%d.%H%M')'%{?dist}/' "${spec_file}"

changelog_commit_msg="* $(date '+%a %b %d %Y') Build System $(get_tag "$spec_file" version)\\
- build an RPM from commit $(git rev-parse $gear_treeish)\\
"

if ! grep -q '%changelog' "$spec_file"; then
    echo -e '\n%changelog' >> "$spec_file"
fi
sed -i "s/%changelog.*/%changelog\\
$changelog_commit_msg/" "$spec_file"

gear-rpm -ba "$spec_file"
